package provider

import (
	"context"
	"fmt"
	"regexp"
	"strconv"
	"terraform-provider-mixpanel/internal/mixpanel"

	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var (
	_ resource.Resource                = &serviceAccountResource{}
	_ resource.ResourceWithConfigure   = &serviceAccountResource{}
	_ resource.ResourceWithImportState = &serviceAccountResource{}
)

func NewServiceAccountResource() resource.Resource {
	return &serviceAccountResource{}
}

type serviceAccountResource struct {
	client *mixpanel.Client
}

type ServiceAccountModel struct {
	Id           types.Int64  `tfsdk:"id"`
	Username     types.String `tfsdk:"username"`
	FullUsername types.String `tfsdk:"full_username"`
	Role         types.String `tfsdk:"role"`
	Secret       types.String `tfsdk:"secret"`
}

// Mixpanel appends a suffix to the username: "foo" becomes "foo.1a2b3c.mp-service-account".
var serviceAccountUsernameSuffix = regexp.MustCompile(`\.[^.]+\.mp-service-account$`)

func (r *serviceAccountResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*mixpanel.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *mixpanel.Client, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)
		return
	}

	r.client = client
}

func (r *serviceAccountResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_service_account"
}

// requiresReplaceUnlessImported forces a replace on change, except when the
// state value is null, which happens after an import since the API doesn't
// return the role.
var requiresReplaceUnlessImported = stringplanmodifier.RequiresReplaceIf(
	func(_ context.Context, req planmodifier.StringRequest, resp *stringplanmodifier.RequiresReplaceIfFuncResponse) {
		resp.RequiresReplace = !req.StateValue.IsNull()
	},
	"Changing the value forces a replacement, unless the resource was imported.",
	"Changing the value forces a replacement, unless the resource was imported.",
)

func (r *serviceAccountResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Organization service account. The secret is only returned by Mixpanel at creation: " +
			"it can't be recovered on import, and rotating it means replacing the resource.",
		Attributes: map[string]schema.Attribute{
			"id": schema.Int64Attribute{
				Computed: true,
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.UseStateForUnknown(),
				},
			},
			"username": schema.StringAttribute{
				Required: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"full_username": schema.StringAttribute{
				MarkdownDescription: "Username generated by Mixpanel, `<username>.<random>.mp-service-account`. Use it with `secret` to authenticate.",
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"role": schema.StringAttribute{
				MarkdownDescription: "Organization role (`admin`, `analyst` or `consumer`, service accounts can't be owners). Mixpanel's default applies when unset.",
				Optional:            true,
				PlanModifiers: []planmodifier.String{
					requiresReplaceUnlessImported,
				},
			},
			"secret": schema.StringAttribute{
				MarkdownDescription: "Service account secret. Only known when the resource was created by Terraform, null after an import.",
				Computed:            true,
				Sensitive:           true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
		},
	}
}

func (r *serviceAccountResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan ServiceAccountModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	serviceAccount, err := r.client.CreateServiceAccount(plan.Username.ValueString(), plan.Role.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Unable to create Mixpanel Service Account", err.Error())
		return
	}

	plan.Id = types.Int64Value(serviceAccount.Id)
	plan.FullUsername = types.StringValue(serviceAccount.Username)
	plan.Secret = types.StringValue(serviceAccount.Token)

	resp.Diagnostics.Append(resp.State.Set(ctx, plan)...)
}

func (r *serviceAccountResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state ServiceAccountModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	serviceAccount, err := r.client.GetServiceAccount(state.Id.ValueInt64())
	if err != nil {
		resp.Diagnostics.AddError(
			"Error Reading Mixpanel Service Account",
			"Could not read Mixpanel service account ID "+strconv.FormatInt(state.Id.ValueInt64(), 10)+": "+err.Error(),
		)
		return
	}
	if serviceAccount == nil {
		resp.State.RemoveResource(ctx)
		return
	}

	// Role and secret aren't returned by the API, keep them from state.
	state.FullUsername = types.StringValue(serviceAccount.Username)
	state.Username = types.StringValue(serviceAccountUsernameSuffix.ReplaceAllString(serviceAccount.Username, ""))

	resp.Diagnostics.Append(resp.State.Set(ctx, state)...)
}

// Update is only reached when setting the role of an imported service account,
// every other change forces a replacement.
func (r *serviceAccountResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan, state ServiceAccountModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Null after an import, and it can't be recovered.
	plan.Secret = state.Secret

	resp.Diagnostics.Append(resp.State.Set(ctx, plan)...)
}

func (r *serviceAccountResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state ServiceAccountModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	err := r.client.DeleteServiceAccount(state.Id.ValueInt64())
	if err != nil && !mixpanel.IsNotFound(err) {
		resp.Diagnostics.AddError("Unable to delete Mixpanel Service Account", err.Error())
	}
}

func (r *serviceAccountResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	id, err := strconv.ParseInt(req.ID, 10, 64)
	if err != nil {
		resp.Diagnostics.AddError("Invalid ID", "ID must be an integer")
		return
	}

	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), id)...)
}
